name: Open PRs Notification
on:
  schedule:
    - cron:  '15 10 * * *'
jobs:
  open-prs-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Open PRs Notification
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: "https://github.com/Constructor-io/zerolog-sentry"
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          PR_LIST=$(gh pr list --repo $REPOSITORY)
          echo "PR List: $PR_LIST"
          
          if [[ $PR_LIST == "" ]]; then
            echo "No open PRs found."
            exit 0
          else
            SLACK_MESSAGE="{\"text\": \"*Issue:* Found open PRs.\n*Repository:* $REPOSITORY\"}"
            SLACK_WEBHOOK_RESPONSE=$(curl -X POST -H 'Content-type: application/json' --data "$SLACK_MESSAGE" $SLACK_WEBHOOK_URL)
            if [[ $SLACK_WEBHOOK_RESPONSE == "ok" ]]; then
              echo "Slack message sent successfully."
              exit 0
            else
              echo "Slack message failed to send with error: $SLACK_WEBHOOK_RESPONSE"
              exit 1
            fi
          fi
